packageExtensions:
    'eslint-config-next@13.4.2':
        dependencies:
            'next': 13.4.2
            'react': 18.2.0
            'react-dom': 18.2.0

yarnPath: .yarn/releases/yarn-3.5.1.cjs
